### ISSUE TITLE
The AI doesn't work

### ISSUE THREAD

**Issue by artur3333** [EXELVI/snake#1]
Dear Exelvi,
After waiting many hours the AI has not learned anything and does not work.

**Comment by EXELVI** [comment]
Hi,

Thank you for trying out the project and for your patience. I apologize for any confusion caused. As mentioned in the README, the AI feature is currently non-functional and is more of a placeholder for future development. 

If you're interested in contributing to or improving the AI, I would be happy to discuss potential ideas or guide you through the existing code. For now, though, the game should work perfectly in manual mode.

Thanks again for your understanding!
